In [1]:
import pandas as pd
import numpy as np

In [2]:
a = [1,2,3]
myvar = pd.Series(a)
print(myvar)

0    1
1    2
2    3
dtype: int64

In [3]:
# agressive cut strategy
calories = {"day 1": 420, "day 2": 380, "day 3": 390}
calories = pd.Series(calories, index=["day 1","day 2"])
print(calories)

day 1    420
day 2    380
dtype: int64

In [4]:
data = {
    "calories": [420, 380, 500],
     "duration": [50, 40, 45]
}
dataframe = pd.DataFrame(data, index=["day 1", "day 2", "day 3"])
dataframe

       calories  duration
day 1       420        50
day 2       380        40
day 3       500        45

In [5]:
dataframe.iloc[:-1,:]

       calories  duration
day 1       420        50
day 2       380        40

In [6]:
print(dataframe['duration'])

day 1    50
day 2    40
day 3    45
Name: duration, dtype: int64

In [7]:
s1 = pd.Series([10, 20, 30], index=['a','b','c'])
s2 = pd.Series([10, 20, 30], index=['a','b','d'])
s1 + s2

a    20.0
b    40.0
c     NaN
d     NaN
dtype: float64